language: php

php:
  - 7.1
  - 7.2
  - 7.3

env:
  - DB=mysql

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS test;" -uroot; fi
  # update root password
  - if [[ "$DB" == "mysql" ]]; then mysql -e "set password for 'root'@'localhost'=password('123456');" -uroot; fi
  - cd ~
  # git clone jasydong/cubephp
  - git clone https://github.com/jasydong/cubephp.git
  - cd cubephp
  - composer install

# run sample command
script: phpunit

# configure notifications
notifications:
  email: "jasydong@qq.com"
